---
openapi: 3.0.1
info:
  title: Time Capsule API
  version: v1
  description: API for managing time messages in a time capsule
paths:
  "/time_messages":
    post:
      summary: Create a TimeMessage
      tags:
      - TimeMessages
      parameters: []
      responses:
        '201':
          description: time_message created
        '422':
          description: invalemail request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                content:
                  type: string
                date_to_open:
                  type: string
                  format: date-time
              required:
              - user_email
              - content
              - date_to_open
    get:
      summary: List all TimeMessages
      tags:
      - TimeMessages
      responses:
        '200':
          description: list of time_messages
  "/time_messages/{email}":
    parameters:
    - name: email
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a TimeMessage
      tags:
      - TimeMessages
      responses:
        '200':
          description: time_message found
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: integer
                  user_email:
                    type: string
                  content:
                    type: string
                  date_to_open:
                    type: string
                    format: date-time
                required:
                - email
                - user_email
                - content
                - date_to_open
        '404':
          description: time_message not found
    patch:
      summary: Updates a TimeMessage
      tags:
      - TimeMessages
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: time_message updated
        '422':
          description: invalemail request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                date_to_open:
                  type: string
                  format: date-time
    delete:
      summary: Deletes a TimeMessage
      tags:
      - TimeMessages
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: time_message deleted
        '404':
          description: time_message not found
  "/users":
    get:
      summary: List all Users
      tags:
      - Users
      responses:
        '200':
          description: list of users
    post:
      summary: Create a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalemail request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/users/{email}":
    parameters:
    - name: email
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a User
      tags:
      - Users
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: integer
                  email:
                    type: string
                required:
                - email
                - email
        '404':
          description: user not found
    patch:
      summary: Updates a User
      tags:
      - Users
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user updated
        '422':
          description: invalemail request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
    delete:
      summary: Deletes a User
      tags:
      - Users
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
